# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jcaychob
# "service" is the name of this project. This will also be added to your AWS resource names.
service: indra-aws-interview

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:851725407776:table/AutorTable

functions:
  createActor:
    handler: src/presentation/actor.createActor
    events:
      - http:
          path: /actor
          method: post
  getActorById:
    handler: src/presentation/actor.getById
    events:
      - http:
          path: /actor/{id}
          method: get
  getAllActors:
    handler: src/presentation/actor.getAll
    events:
      - http:
          path: /
          method: get
resources:
  Resources:
    AutorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AutorTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
